# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w7IUecJkE-1zJXxd1UwS81wgEK_9zNxw
"""



from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""

import pandas as pd
df= pd.read_csv('/content/drive/MyDrive/matches.csv')
df.head()

